# Parent directories for data
DIR:
  raw:                   data/raw            # where uncompressed data is or should be downloaded
  psf:                   data/psf            # where psf for deconvolutions are
  dataset:               data/dataset        # where data is
  drawing:               data/drawn_cyto     # Basile 2D drawing of cytonemes for pipeline validation
  output:                data/output         # where script outputs should be
  model:                 data/output/model   # where we save our models
  graph:                 data/output/graph   # where we save our graphes
  figure:                data/output/figure  # where we save our figures
  metrics:               data/output/csv     # where we output our metrics

# volumes
VOLUME:
  input:                 data/dataset/input          # where labeled X inputs are
  rl_input:              data/dataset/rl_input       # where labeled denoised X inputs are
  target:                data/dataset/target         # where labeled Y inputs are
  soft_target:           data/dataset/soft_target    # where soft labeled Y inputs are
  weight:                data/dataset/weight         # where inputs sample weights are
  soft_weight:           data/dataset/soft_weight    # where inputs soft sample weights are
  ilastik_target:        data/dataset/ilastik        # where we converted the target to be compatible with ilastik
  unlabeled:             data/dataset/unlabeled      # where unlabeled inputs are
  rl_unlabeled:          data/dataset/rl_unlabeled   # where denoised unlabeled inputs are
  unlabeled_target:      data/dataset/unlabeled_target       # where unlabeled self generated targets are
  unlabeled_soft_target: data/dataset/unlabeled_soft_target  # where unlabeled self generated targets are
  unlabeled_weight:      data/dataset/unlabeled_weight       # where unlabeled self generated weights are
  unlabeled_soft_weight: data/dataset/unlabeled_soft_weight  # where unlabeled self generated weights are
  restore:               data/output/restore         # where we save the denoised volumes
  ilastik:               data/output/ilastik         # where we save the segmented volumes via ilastik
  threshold:             data/output/threshold       # where we save the segmented volumes via threshold
  unet2d:                data/output/unet2d          # where we save the segmented volumes via UNet2D
  unet3d:                data/output/unet3d          # where we save the segmented volumes via UNet3D
  imagej:                data/output/imagej          # where we converted the predictions to be compatible with imagej

# For input preprocessing
PREPROCESS:
  n_cls:   3    # number of classes
  rl_iter: 25   # number of Richardson-Lucy iterations
  blur:    1.5  # sigma for gaussian blur when generating soft labels
  distance:
    - 0.26
    - 0.1201058
    - 0.1201058

MODEL:
  backbone:   VGG16        # UNet backbone
  pretrained: 1            # if encoder is pretrained on imagenet
  dropout:    0.3          # dropout rate
  
TRAINING:
  epoch:      40           # number of epoch
  patience:   10           # early stop patience
  validation:              # volumes used for validation
    - ctrl2
    - slik2
  evaluation:              # volumes used for evaluation
    - ctrl1
    - slik1
